In [1]:
import pandas as pd

In [2]:
Series = pd.Series([1,2,3,4,5,6,7,8] , dtype=float)
print(Series)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
dtype: float64

In [3]:
df = pd.DataFrame ({ 
        'Name' : ["noman" , "ali" , "amjad", "ansar" , "affan" , "anwar"],
        'age' : [29 , 34 , 23 , 45 , 12 , 89],
        'city' : ["gujranwala" , "lahore" , "islamabad", "karachi" , "kashmir", "pindi"]
    })
print(df)

    Name  age        city
0  noman   29  gujranwala
1    ali   34      lahore
2  amjad   23   islamabad
3  ansar   45     karachi
4  affan   12     kashmir
5  anwar   89       pindi

In [4]:
print(df.head())

    Name  age        city
0  noman   29  gujranwala
1    ali   34      lahore
2  amjad   23   islamabad
3  ansar   45     karachi
4  affan   12     kashmir

In [5]:
print(df.tail())

    Name  age       city
1    ali   34     lahore
2  amjad   23  islamabad
3  ansar   45    karachi
4  affan   12    kashmir
5  anwar   89      pindi

In [6]:
df.describe()

             age
count   6.000000
mean   38.666667
std    27.001235
min    12.000000
25%    24.500000
50%    31.500000
75%    42.250000
max    89.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   age     6 non-null      int64
 2   city    6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [8]:
df.iloc[1]

Name       ali
age         34
city    lahore
Name: 1, dtype: object

In [9]:
df["age"]

0    29
1    34
2    23
3    45
4    12
5    89
Name: age, dtype: int64

In [10]:
df[["Name" , "city"]]

    Name        city
0  noman  gujranwala
1    ali      lahore
2  amjad   islamabad
3  ansar     karachi
4  affan     kashmir
5  anwar       pindi

In [13]:
df.iloc[2]

Name        amjad
age            23
city    islamabad
Name: 2, dtype: object

In [33]:
df = pd.read_csv("Data.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [22]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [23]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

In [41]:
df.iloc[14:23]

    Duration          Date  Pulse  Maxpulse  Calories
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0